# Generated by Django 3.1.3 on 2020-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20201120_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=256, verbose_name='7ACA03E9A81D0650DECDD5F87490CA9B'),
        ),
    ]
